### PR TITLE
Add node_modules check

### PR DESCRIPTION
**Pull request by zacksmash**
Check if the given path contains node_modules and open file accordingly. This assumes that the node_modules directory is in the project root.

### CODE REVIEW

**Comment by abemedia** [comment]
@penx any showstoppers? I could do with with this functionality too...

**Comment by penx** [comment]
I’m not certain the change on line 66/86 won’t break something and it was a while since I wrote it. I have limited time to look at the moment though the contribution is very welcome. 

Would be happy to add either of you as a contributor if you feel up to reviewing. 

At some point we need some unit tests to make sure things aren’t breaking.

**Comment by zacksmash** [comment]
@penx I think the issue I was running into with line 86 was that if the file didn't exist, it would still attempt to open something, which I didn't feel was expected behavior. I left it commented, just in case, but I've been using a private version of this plugin in Atom since I made this pull request and haven't noticed any strange behavior. Let me know if there's anything else I can do.

Thanks!

**Comment by penx** [comment]
I either want to go back and manually retest this before I merge in, or have at least 1-2 unit tests in the project so if anything breaks in future it will be easier to automate/fix.

If anyone wants to look at some very basic unit tests then I will consider merging, otherwise it will need to wait until I have some spare time.

**Comment by penx** [comment]
> @penx I think the issue I was running into with line 86 was that if the file didn't exist, it would still attempt to open something, which I didn't feel was expected behavior

@zacksmash this is intentional - it mirrors what js-hyperclick does. It allows a developer to write an import statement before creating the file that they want to link to, then click through to it to start editing.

**Comment by penx** [comment]
the problem here, of course, is I don't have any unit tests :-)

**Comment by zacksmash** [comment]
> @zacksmash this is intentional - it mirrors what js-hyperclick does. It allows a developer to write an import statement before creating the file that they want to link to, then click through to it to start editing.

@penx That makes sense. I probably shouldn't have added that into the PR. I can remove and resubmit, if you'd like!

**Pull request closed without merging**
